### PR TITLE
Support custom cache drivers in orm.cache.factory

### PR DESCRIPTION
**Pull request by c960657**
The cache driver factory, orm.cache.factory, only supports the predefined cache drivers.

With this PR, the factory also supports custom cache drivers.

### CODE REVIEW

**Comment by simensen** [comment]
I think this should be fine. Not sure if changing the structure of an Exception message would constitute a BC break? What do you think?

**Comment by c960657** [comment]
People matching the human-readable exception message should not be surprised by wording changes.

On the other hand, the new message is not a big improvement over the old one (it might even be less helpful in the common usecase where someone just made a spelling mistake when specifying the driver), so I will revert the change.

**Comment by simensen** [comment]
@c960657 I actually like it; just not sure how safe it is. :) You could add in parens "(is it spelled correctly?)" or something?

**Comment by c960657** [comment]
Done :-)

I think this is a minor BC break that only affects some very unusual use-cases, so I think it is acceptable.

**Comment by simensen** [comment]
@c960657 thanks! appreciate it. :)

**Comment by hkdobrev** [comment]
@simensen Could you release a new stable version including this enhancement? Thank you!

**Comment by hkdobrev** [comment]
@simensen 👋 Do you think a new version could be released with this? E.g. `2.1.0`.

**Pull request merged**
